/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("net.java.dev.jna:jna:5.13.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "traffic.sensor.integration.App"

    applicationDefaultJvmArgs = listOf(
        "--enable-native-access=ALL-UNNAMED"
    )
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Tarefa para compilar o C
val compileC by tasks.registering(Exec::class) {
    group = "build"
    description = "Compila o código C nativo usando Make"
    
    // Define o diretório de trabalho como a pasta do projeto 'app'
    workingDir = layout.projectDirectory.asFile
    
    // Executa 'make' (ele vai ler o Makefile que criamos)
    commandLine("make")
}

// Tarefa para limpar o C
val cleanC by tasks.registering(Exec::class) {
    group = "build"
    description = "Limpa os binários C compilados"
    workingDir = layout.projectDirectory.asFile
    commandLine("make", "clean")
}

// Conecta as tarefas do Java com as do C
tasks.named("compileJava") {
    dependsOn(compileC) // Antes de compilar Java, compila o C
}

tasks.named("clean") {
    dependsOn(cleanC) // Quando limpar Java, limpa o C também
}